### ISSUE TITLE
Including files in a helm package - is this possible?

### ISSUE THREAD

**Issue by msmithson-roku** [abrisco/rules_helm#74]
Helm allows you to load files using .Files.get - https://helm.sh/docs/chart_template_guide/accessing_files/

I can't work out a way to include files in the chart root folder using `helm_package` (other than Chart.yaml or values.yaml). Without this `rules_helm` can't be used with chart that use `.Files.get` as this is not allowed to access files in the `templates` folder.

Is there a way to do this that I can missing?

**Comment by abrisco** [comment]
This should work as long as the files are inputs to the rule. Can you provide an example of something that works with helm directly but not in `rules_helm`?

**Comment by msmithson-roku** [comment]
As far as I can see `helm_package` does not allow you to specify `inputs` - other the `chart`, `values` or `templates`.

Try to specify `inputs` or add the additional files to `deps` causes errors.

An example if specifying a ConfigMap where the data comes from a file. e.g.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-mappings
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
data:
  mappings.yaml: |-
    {{- .Files.Get "mappings.yaml" | trimSuffix "\n" | nindent 4 }}
```

For this to work `mappings.yaml` needs to packaged with the Chart (and not in the templates folder). I can't find a way to do this with `rules_helm`.

At the moment we are using `pkg_tar` to add these files to the chart created using `helm_package` and then using `helm_import` so we can use it a chart in other rules. Not ideal.
